export const ANALYTICS_CHART_KEYS = {
  BUSINESS_HEALTH_SCORE: "businessHealthScore",
  FORECAST_VS_ACTUAL: "forecastVsActual",
  GROWTH_COMPARISON: "growthComparison",
  MONTHLY_BUSINESS_SCORECARD: "monthlyBusinessScorecard",
  TOP_OPPORTUNITIES: "topOpportunities",
  COST_PER_QUALIFIED_LEAD: "costPerQualifiedLead",
  SOURCE_TO_REVENUE_COMPARISON: "sourceToRevenueComparison",
  AVG_DEAL_CLOSURE_TIME: "avgDealClosureTime",
  FUNNEL_CONVERSION: "funnelConversion",
  PIPELINE_STAGE_DISTRIBUTION: "pipelineStageDistribution",
  STAGE_CONVERSION_RATE: "stageConversionRate",
  STAGE_DROP_OFF: "stageDropOff",
  STUCK_DEALS: "stuckDeals",
  AVERAGE_DEAL_SIZE: "averageDealSize",
  FORECAST_REVENUE: "forecastRevenue",
  REVENUE_BY_AGENT: "revenueByAgent",
  REVENUE_BY_LOCATION: "revenueByLocation",
  REVENUE_BY_PROJECT: "revenueByProject",
  REVENUE_TREND: "revenueTrend",
  TARGET_VS_ACHIEVEMENT: "targetVsAchievement",
  WON_VS_LOST_DEALS: "wonVsLostDeals",
  HIGH_RISK_DEALS: "highRiskDeals",
  LOST_LEAD_REASONS: "lostLeadReasons",
  RISK_SCORE_DISTRIBUTION: "riskScoreDistribution",
  CHANNEL_PERFORMANCE: "channelPerformance",
  OPEN_RATE: "openRate",
  CLICK_RATE: "clickRate",
  REPLY_RATE: "replyRate",
  DELIVERY_STATS: "deliveryStats",
  SOURCE_PERFORMANCE: "sourcePerformance",
  PROJECT_PERFORMANCE: "projectPerformance",
  AREA_PERFORMANCE: "areaPerformance",
  TOP_PERFORMERS: "topPerformers",
  ALERT_SUMMARY: "alertSummary",
  FORECAST_INSIGHT: "forecastInsight",
} as const;

export type AnalyticsChartKey =
  (typeof ANALYTICS_CHART_KEYS)[keyof typeof ANALYTICS_CHART_KEYS];

export const ANALYTICS_CHART_KEY_LIST: AnalyticsChartKey[] = Object.values(
  ANALYTICS_CHART_KEYS
);

export const ANALYTICS_PRIMARY_CHART_KEYS: AnalyticsChartKey[] = [
  ANALYTICS_CHART_KEYS.BUSINESS_HEALTH_SCORE,
  ANALYTICS_CHART_KEYS.FORECAST_VS_ACTUAL,
  ANALYTICS_CHART_KEYS.GROWTH_COMPARISON,
  ANALYTICS_CHART_KEYS.MONTHLY_BUSINESS_SCORECARD,
  ANALYTICS_CHART_KEYS.TOP_OPPORTUNITIES,
  ANALYTICS_CHART_KEYS.REVENUE_TREND,
  ANALYTICS_CHART_KEYS.FORECAST_REVENUE,
  ANALYTICS_CHART_KEYS.TARGET_VS_ACHIEVEMENT,
];

export const ANALYTICS_REVENUE_CHART_KEYS: AnalyticsChartKey[] = [
  ANALYTICS_CHART_KEYS.FORECAST_REVENUE,
  ANALYTICS_CHART_KEYS.REVENUE_BY_AGENT,
  ANALYTICS_CHART_KEYS.REVENUE_BY_LOCATION,
  ANALYTICS_CHART_KEYS.REVENUE_BY_PROJECT,
  ANALYTICS_CHART_KEYS.REVENUE_TREND,
  ANALYTICS_CHART_KEYS.TARGET_VS_ACHIEVEMENT,
  ANALYTICS_CHART_KEYS.SOURCE_TO_REVENUE_COMPARISON,
  ANALYTICS_CHART_KEYS.AVERAGE_DEAL_SIZE,
];

export const ANALYTICS_PIPELINE_CHART_KEYS: AnalyticsChartKey[] = [
  ANALYTICS_CHART_KEYS.FUNNEL_CONVERSION,
  ANALYTICS_CHART_KEYS.PIPELINE_STAGE_DISTRIBUTION,
  ANALYTICS_CHART_KEYS.STAGE_CONVERSION_RATE,
  ANALYTICS_CHART_KEYS.STAGE_DROP_OFF,
  ANALYTICS_CHART_KEYS.STUCK_DEALS,
  ANALYTICS_CHART_KEYS.WON_VS_LOST_DEALS,
  ANALYTICS_CHART_KEYS.HIGH_RISK_DEALS,
  ANALYTICS_CHART_KEYS.RISK_SCORE_DISTRIBUTION,
  ANALYTICS_CHART_KEYS.AVG_DEAL_CLOSURE_TIME,
];

export const ANALYTICS_MARKETING_CHART_KEYS: AnalyticsChartKey[] = [
  ANALYTICS_CHART_KEYS.COST_PER_QUALIFIED_LEAD,
  ANALYTICS_CHART_KEYS.SOURCE_TO_REVENUE_COMPARISON,
  ANALYTICS_CHART_KEYS.SOURCE_PERFORMANCE,
  ANALYTICS_CHART_KEYS.LOST_LEAD_REASONS,
  ANALYTICS_CHART_KEYS.CHANNEL_PERFORMANCE,
  ANALYTICS_CHART_KEYS.OPEN_RATE,
  ANALYTICS_CHART_KEYS.CLICK_RATE,
  ANALYTICS_CHART_KEYS.REPLY_RATE,
  ANALYTICS_CHART_KEYS.DELIVERY_STATS,
];

export const ANALYTICS_PERFORMANCE_CHART_KEYS: AnalyticsChartKey[] = [
  ANALYTICS_CHART_KEYS.PROJECT_PERFORMANCE,
  ANALYTICS_CHART_KEYS.AREA_PERFORMANCE,
  ANALYTICS_CHART_KEYS.TOP_PERFORMERS,
  ANALYTICS_CHART_KEYS.REVENUE_BY_AGENT,
  ANALYTICS_CHART_KEYS.REVENUE_BY_LOCATION,
  ANALYTICS_CHART_KEYS.REVENUE_BY_PROJECT,
  ANALYTICS_CHART_KEYS.TOP_OPPORTUNITIES,
];

export const ANALYTICS_INSIGHT_CHART_KEYS: AnalyticsChartKey[] = [
  ANALYTICS_CHART_KEYS.ALERT_SUMMARY,
  ANALYTICS_CHART_KEYS.FORECAST_INSIGHT,
  ANALYTICS_CHART_KEYS.BUSINESS_HEALTH_SCORE,
  ANALYTICS_CHART_KEYS.HIGH_RISK_DEALS,
];

export const ANALYTICS_COMMUNICATION_CHART_KEYS: AnalyticsChartKey[] = [
  ANALYTICS_CHART_KEYS.CHANNEL_PERFORMANCE,
  ANALYTICS_CHART_KEYS.OPEN_RATE,
  ANALYTICS_CHART_KEYS.CLICK_RATE,
  ANALYTICS_CHART_KEYS.REPLY_RATE,
  ANALYTICS_CHART_KEYS.DELIVERY_STATS,
];

export const isAnalyticsChartKey = (
  value: string
): value is AnalyticsChartKey => {
  return ANALYTICS_CHART_KEY_LIST.includes(value as AnalyticsChartKey);
};

export const getAnalyticsChartGroup = (
  key: AnalyticsChartKey
):
  | "primary"
  | "revenue"
  | "pipeline"
  | "marketing"
  | "performance"
  | "insight"
  | "communication"
  | "other" => {
  if (ANALYTICS_PRIMARY_CHART_KEYS.includes(key)) return "primary";
  if (ANALYTICS_REVENUE_CHART_KEYS.includes(key)) return "revenue";
  if (ANALYTICS_PIPELINE_CHART_KEYS.includes(key)) return "pipeline";
  if (ANALYTICS_MARKETING_CHART_KEYS.includes(key)) return "marketing";
  if (ANALYTICS_PERFORMANCE_CHART_KEYS.includes(key)) return "performance";
  if (ANALYTICS_INSIGHT_CHART_KEYS.includes(key)) return "insight";
  if (ANALYTICS_COMMUNICATION_CHART_KEYS.includes(key)) return "communication";
  return "other";
};

export const ANALYTICS_DEFAULT_VISIBLE_CHART_KEYS: AnalyticsChartKey[] = [
  ANALYTICS_CHART_KEYS.BUSINESS_HEALTH_SCORE,
  ANALYTICS_CHART_KEYS.FORECAST_VS_ACTUAL,
  ANALYTICS_CHART_KEYS.TOP_OPPORTUNITIES,
  ANALYTICS_CHART_KEYS.FUNNEL_CONVERSION,
  ANALYTICS_CHART_KEYS.REVENUE_TREND,
  ANALYTICS_CHART_KEYS.TARGET_VS_ACHIEVEMENT,
  ANALYTICS_CHART_KEYS.WON_VS_LOST_DEALS,
  ANALYTICS_CHART_KEYS.HIGH_RISK_DEALS,
];

export const ANALYTICS_EXPORTABLE_CHART_KEYS: AnalyticsChartKey[] = [
  ...ANALYTICS_CHART_KEY_LIST,
];

export const ANALYTICS_COMPARISON_ENABLED_KEYS: AnalyticsChartKey[] = [
  ANALYTICS_CHART_KEYS.BUSINESS_HEALTH_SCORE,
  ANALYTICS_CHART_KEYS.FORECAST_VS_ACTUAL,
  ANALYTICS_CHART_KEYS.GROWTH_COMPARISON,
  ANALYTICS_CHART_KEYS.MONTHLY_BUSINESS_SCORECARD,
  ANALYTICS_CHART_KEYS.COST_PER_QUALIFIED_LEAD,
  ANALYTICS_CHART_KEYS.AVG_DEAL_CLOSURE_TIME,
  ANALYTICS_CHART_KEYS.AVERAGE_DEAL_SIZE,
  ANALYTICS_CHART_KEYS.REVENUE_TREND,
  ANALYTICS_CHART_KEYS.TARGET_VS_ACHIEVEMENT,
  ANALYTICS_CHART_KEYS.OPEN_RATE,
  ANALYTICS_CHART_KEYS.CLICK_RATE,
  ANALYTICS_CHART_KEYS.REPLY_RATE,
];

export const ANALYTICS_REALTIME_FRIENDLY_KEYS: AnalyticsChartKey[] = [
  ANALYTICS_CHART_KEYS.BUSINESS_HEALTH_SCORE,
  ANALYTICS_CHART_KEYS.TOP_OPPORTUNITIES,
  ANALYTICS_CHART_KEYS.STUCK_DEALS,
  ANALYTICS_CHART_KEYS.HIGH_RISK_DEALS,
  ANALYTICS_CHART_KEYS.ALERT_SUMMARY,
  ANALYTICS_CHART_KEYS.CHANNEL_PERFORMANCE,
  ANALYTICS_CHART_KEYS.DELIVERY_STATS,
];

export const ANALYTICS_CHART_STORAGE_KEYS = {
  SELECTED_CHARTS: "mei-analytics-selected-charts",
  SAVED_VIEW: "mei-analytics-saved-view",
  CHART_ORDER: "mei-analytics-chart-order",
  FILTERS: "mei-analytics-filters",
  DATE_RANGE: "mei-analytics-date-range",
  COMPARE_MODE: "mei-analytics-compare-mode",
} as const;

export type AnalyticsChartStorageKey =
  (typeof ANALYTICS_CHART_STORAGE_KEYS)[keyof typeof ANALYTICS_CHART_STORAGE_KEYS];

export default ANALYTICS_CHART_KEYS;